### ISSUE TITLE
send bulk events

### ISSUE THREAD

**Issue by Malkiz** [loggly/loggly-jslogger#15]
I would like to use this library to send bulk events to Loggly.
I tried changing the URL to /bulk/ instead of /inputs/ but it returns a server error.

**Comment by mostlyjason** [comment]
The bulk endpoint requires a POST request. Also it requires line-separated events. This is possible, but would require more coding.

**Comment by susilm** [comment]
We are not going to implement this feature in the near term, therefore closing the ticket now. But feel free to prepare PR and reopen this ticket.
