### ISSUE TITLE
Filter out types of errors

### ISSUE THREAD

**Issue by dandv** [loggly/loggly-jslogger#19]
Is there a way to filter out errors, such as those generated by browser extensions installed by the user, or thrown by 3rd-party libraries?

AirBrake has this feature: https://github.com/airbrake/airbrake-js#filtering-errors

**Comment by mostlyjason** [comment]
Feel free to submit a pull request!

**Comment by susilm** [comment]
We are not going to implement this feature in the near term, therefore closing the ticket now. But feel free to prepare PR and reopen this ticket.
