### ISSUE TITLE
sending tags?

### ISSUE THREAD

**Issue by omouse** [loggly/loggly-jslogger#2]
is there a way to attach a tag to the "push"? or do I do that manually by filtering on fields in the JSON objects I'm logging?

**Comment by psquickitjayant** [comment]
It looks like tag support has been implemented in the latest update.

**Comment by JordanPotter** [comment]
Seems tag support was removed. Really looking forward to support for this feature!

**Comment by boneskull** [comment]
:+1:

**Comment by psquickitjayant** [comment]
Hoping @mostlyjason  we will get tag support soon.

**Comment by pbojinov** [comment]
looks like tag support was removed in https://github.com/loggly/loggly-jslogger/commit/ffe2b403530ffb6260174d591f99624815273b1e

**Comment by psquickitjayant** [comment]
Added option in #25

**Comment by psquickitjayant** [comment]
@omouse  added support for tags in the latest update.
