### ISSUE TITLE
FYI: loggly blocked by default by ad blockers

### ISSUE THREAD

**Issue by dandv** [loggly/loggly-jslogger#20]
https://easylist-downloads.adblockplus.org/easyprivacy.txt

![image](https://cloud.githubusercontent.com/assets/33569/8665063/6913e3be-2994-11e5-9c2a-885845a785f3.png)

![loggly blocked by ad blockers](https://cloud.githubusercontent.com/assets/33569/8664867/223698c6-2992-11e5-9bc8-8c457f5cd0fe.png)

**Comment by dandv** [comment]
A solution to this would be supporting an option to specify the URL of the "Loggly" host, so that we can proxy requests through our own server.

**Comment by dandv** [comment]
Studies done by Adobe and others estimated that 40% (forty percent) of users 18-29 use Ad Blocking, and the percentage grew by 70% between June 2013 and June 14. http://blog.pagefair.com/2014/adblocking-report/. The study was done in 2014.

What is Loggly's solution to this?

**Comment by mostlyjason** [comment]
Thanks for raising this issue! Let me check with the team and follow up here.

**Comment by mostlyjason** [comment]
Apparently adblockplus has easy privacy turned off by default. That's the list we are on. I figured it's a much smaller percentage who use that? Also seems like the proxy is the only solution, but that is more inconvenient for people to set up.

**Comment by mostlyjason** [comment]
Added proxy support in #27 Closing
