### ISSUE TITLE
Is the JS logger on npm?

### ISSUE THREAD

**Issue by dandv** [loggly/loggly-jslogger#21]
https://www.npmjs.com/search?q=Loggly shows too many results. If the jslogger is on npm, a link in the README would be great.

**Comment by dandv** [comment]
Given the lack of releases in this repo, I guess the answer is "no".

**Comment by mostlyjason** [comment]
We actually have node-specific libraries including node-loggly and winston-loggly https://www.loggly.com/docs/nodejs-logs/

**Comment by dandv** [comment]
Maybe on Bower then?

http://bower.io/search/?q=loggly

**Comment by dandv** [comment]
Thought http://stackoverflow.com/questions/18641899/what-is-the-difference-between-bower-and-npm/31219726#31219726

**Comment by psquickitjayant** [comment]
@dandv  You can find jslogger on bower, As mentioned by @mostlyjason  node has a separate library for the loggly https://www.loggly.com/docs/nodejs-logs/
