### ISSUE TITLE
More precise information about JS errors in 3rd party code - possible?

### ISSUE THREAD

**Issue by dandv** [loggly/loggly-jslogger#22]
I have an error in a 3rd party library, that looks like this in Chrome:

![image](https://cloud.githubusercontent.com/assets/33569/8667111/a8cff2a2-29af-11e5-9b81-299f068c93f3.png)

In Loggly it looks like this:

![image](https://cloud.githubusercontent.com/assets/33569/8667120/eb7bf07e-29af-11e5-98d7-d4fbfa73ab48.png)

Not exactly useful.

Is this possible? [LogEntries doesn't seem to be able to offer better result either](https://github.com/logentries/le_js/issues/51).

**Comment by dandv** [comment]
`window.onerror` doesn't return that information, so I guess it's not possible.

**Comment by dandv** [comment]
Apparently `window.onerror` doesn't return that information, unless [CORS is set up properly](https://bugsnag.com/blog/script-error), which wasn't the case in my setup, judging by the fact that a naive `onerror` handler gets "Script error" and 0.

Yet there must be a way to do this because Rollbar manages to somehow get file and line information:

![image](https://cloud.githubusercontent.com/assets/33569/8670915/ba0646f4-29d5-11e5-9e3a-9898c227dfa2.png)

What's going on above:

0. Ensure Rollbar is installed
1. Produce the error by [clicking on an SVG on the page](https://github.com/piwik/piwik/pull/8346)
2. Add a simple onerror handler that just logs the message, file and line
3. Trigger the error. Note that full information is available.
4. Remove rollbar code from the page and reload.
5. Re-add the simple onerror handler.
6. Trigger the error. Notice how the error handler only gets Script and 0.

Therefore, Rollbar managed to catch the error from the 3rd party script.

**Comment by mostlyjason** [comment]
Interesting, any idea how Rollbar does this? Seems like a useful addition.

**Comment by dandv** [comment]
They've [shared](https://github.com/rollbar/rollbar.js/issues/108) :)

**Comment by psquickitjayant** [comment]
@dandv  try to test this one after hosting your webpage on a server. It gives the script error when you runs the webpage from filesystem as browser does not allow your script to read the actual error message.

**Comment by marcelodeveloper** [comment]
@dandv you can add a crossorigin attribute in <src> tag, You'll be to be able to gets the exception.

**Comment by susilm** [comment]
We are not going to implement this feature in the near term, therefore closing the ticket now. But feel free to prepare PR and reopen this ticket.
