### ISSUE TITLE
Document logglyCollectorDomain 

### ISSUE THREAD

**Issue by dandv** [loggly/loggly-jslogger#23]
Would help alleviate #20 if the developer wants to set up a proxy.

**Comment by dandv** [comment]
I've added an entry to LogEntries' wiki about using a proxy: https://github.com/logentries/le_js/wiki/API#ad-blockers

**Comment by mostlyjason** [comment]
@psquickitjayant can you add this in?

**Comment by psquickitjayant** [comment]
@mostlyjason  done!

**Comment by mostlyjason** [comment]
@psquickitjayant can you close the issue when it's complete? I think this might require a code change

**Comment by psquickitjayant** [comment]
@mostlyjason  @dandv  I am looking into it.

**Comment by psquickitjayant** [comment]
@mostlyjason @dandv  added support in #27
