### ISSUE TITLE
Image Warnings...

### ISSUE THREAD

**Issue by bradschafer** [loggly/loggly-jslogger#3]
I am getting a lot of image warnings in Chrome...

Resource interpreted as Image but transferred with MIME type text/html: "http://logs-01.loggly.com/inputs/d62c2db7-48fa-4105-a0ca.....

It seems we're requesting an image but getting back text/html...

**Comment by kellycampbell** [comment]
I get these warnings even if I don't set the tag. It uses the default tag of 'jslogger'.

**Comment by davidcai** [comment]
I changed the URL to https://logs-01.loggly.com/inputs/token/.gif?PLAINTEXT=..., but I still get the warnings.

**Comment by psquickitjayant** [comment]
@kellycampbell  could you please share your script, it looks like that you are using older version of the script as current script does not use any tag

**Comment by psquickitjayant** [comment]
@davidcai  I have tested with the latest script. It does not show any image warnings.

**Comment by psquickitjayant** [comment]
Try #25

**Comment by psquickitjayant** [comment]
@bradschafer  Seems this to be fixed in the latest update.
