### ISSUE TITLE
400 Bad Request when using NGINX proxy to avoid adblock

### ISSUE THREAD

**Issue by peterwilli** [loggly/loggly-jslogger#33]
Hi,

I'm currently trying to get loggly js logging working trough my nginx network (see: https://github.com/loggly/loggly-jslogger#setup-proxy-for-ad-blockers). Somehow it does not work and always gives me '400 Bad Request'-errors.

I'm using the config file in the example as-is (no changes made) and the API request works just fine if I remove my own domain name from the url and replace it by: `http://logs-01.loggly.com`

So it works when I have no nginx in between, so I believe it's nginx to blame but I just can't place what it could be.

Anyone else having this problem? Thanks!

**Comment by peterwilli** [comment]
***UPDATE***
Figured it out! After some time of debugging, Apparently Loggly doesnt like cloudflare headers. I changes my config to this and everything is fine now:

```
#Proxy to Loggly
location /loggly/ {

    rewrite ^/loggly/(.*)$ /$1 break;  # remove the '/loggly' part from the path, leaving /inputs/xxxxxxxx-xxxx-.../tag/xxx
    proxy_set_header Host logs-01.loggly.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;

    proxy_set_header  CF-IPCountry "";
    proxy_set_header  CF-RAY "";
    proxy_set_header  CF-Visitor "";
    proxy_set_header  CF-Connecting-IP "";

    proxy_pass http://logs-01.loggly.com;
}
```

**Comment by mostlyjason** [comment]
@peterwilli FYI we recently added a new component which should process these events with the CF headers. If you need them try adding them back in when ready.

**Comment by SegersIan** [comment]
I'am still facing issues with CloudFlare headers. So seems it's not entirely fixed ? 🤔

**Comment by Katulus** [comment]
@SegersIan Can you provide more information? This issue is closed for over 3 years. Is your scenario the same as in initial post? Are you using NGINX proxy? Can you provide your configuration, what you send and what you receive?

**Comment by SegersIan** [comment]
@Katulus Sorry, didn't saw your response. My issuer is not NGIX specific, but I noticed that the following header from cloudflare seems to throw a `400` : 
```
Cf-Visitor: {"scheme":"http"}
```
I discovered this by first logging to some service like request bin, and then repeating the same request to the loggly API. 
**This means it's not an NGIX* issue, where should I consider opening this issue?

**Comment by Katulus** [comment]
@SegersIan Thanks for the info. It looks that our endpoint has issues with `{,} and "` in the header value. We need to investigate it a bit more. Your support case was moved to our backlog for further investigation. I can't give you any timeline though.

**Comment by Katulus** [comment]
@SegersIan , this should be now fixed. `cf-visitor` header won't break things anymore. Can you give it a try?
