### ISSUE TITLE
Bower deployment

### ISSUE THREAD

**Issue by ppcano** [loggly/loggly-jslogger#4]
would it be possible that the library can be deployed with bower?

**Comment by ppcano** [comment]
@psquickitjayant ping.

May the `bower.json` file be added to the repository including the current `loggly-jslogger` version.

**Comment by psquickitjayant** [comment]
@ppcano  Sure, I will add it.

**Comment by barlindhaug** [comment]
You need to git tag your releases to get a versioned bower dependency.

Right now I have to use
    
    "loggly-jslogger": "*"

instead of
    "loggly-jslogger": "1.1.0"

**Comment by psquickitjayant** [comment]
@barlindhaug  if you see latest package, it has the version.

**Comment by ppcano** [comment]
@psquickitjayant, setup the version on the `bower.json` file does NOT work

```
    "loggly-jslogger": "2.0.0",
```

As @barlindhaug commented, it could be that you need to git tag your releases.

**Comment by psquickitjayant** [comment]
@ppcano  You are write, I forgot to do that. I will take care from my next release. I am making few more changes in the library. I will make sure to tag the commit.

**Comment by davidgovea** [comment]
+1 for tagging releases, `"loggly-jslogger": "*"` makes me uneasy. 
:+1:

**Comment by psquickitjayant** [comment]
@mostlyjason  this can be closed as the library is on Bower with versions tagged.

**Comment by davidgovea** [comment]
@psquickitjayant @mostlyjason I see no versions tagged.

Here is the output from "bower info loggly-jslogger" ... `No versions available.`

```
% bower info loggly-jslogger 
bower not-cached    git://github.com/loggly/loggly-jslogger.git#*
bower resolve       git://github.com/loggly/loggly-jslogger.git#*
bower checkout      loggly-jslogger#master
bower resolved      git://github.com/loggly/loggly-jslogger.git#c293114921

{
  name: 'loggly-jslogger',
  homepage: 'https://github.com/loggly/loggly-jslogger',
  description: 'A Javascript client to send logs to Loggly.',
  main: 'src/loggly.tracker.js',
  keywords: [
    'loggly-jslogger',
    'jslogger',
    'loggly',
    'log'
  ],
  authors: [
    'Loggly'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ]
}

No versions available.
```

**Comment by davidgovea** [comment]
From bower's [bower.json docs](http://bower.io/docs/creating-packages/)

**version**
String
Deprecated. **Use git or svn tags instead. This field is ignored by Bower.**

**Comment by davidgovea** [comment]
ping ping - would love a proper release!

**Comment by psquickitjayant** [comment]
@davidgovea  I will update today :)

**Comment by psquickitjayant** [comment]
@davidgovea @ppcano  @sirsgriffin @barlindhaug  

Proper release tags are pushed in repo. You can see the versions now with `bower info loggly-jslogger`

```
$ bower info loggly-jslogger
bower loggly-jslogger#*         cached git://github.com/loggly/loggly-jslogger.git#3.0.0
bower loggly-jslogger#*       validate 3.0.0 against git://github.com/loggly/loggly-jslogger.git#*

{
  name: 'loggly-jslogger',
  homepage: 'https://github.com/loggly/loggly-jslogger',
  version: '3.0.0',
  description: 'A Javascript client to send logs to Loggly.',
  main: 'src/loggly.tracker.js',
  keywords: [
    'loggly-jslogger',
    'jslogger',
    'loggly',
    'log'
  ],
  authors: [
    'Loggly'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ]
}

Available versions:
  - 3.0.0
  - 2.0.0
You can request info for a specific version with 'bower info loggly-jslogger#<version>'
```

**Comment by davidgovea** [comment]
@psquickitjayant thank you!

also, thanks for getting full-on tags implemented recently :+1:
