### ISSUE TITLE
Support for levels

### ISSUE THREAD

**Issue by johnfrancisgit** [loggly/loggly-jslogger#59]
Is there support for levels such as info, warn, error etc?
If so, It's missing from the documentation

**Comment by Katulus** [comment]
Hello @johnfrancisgit,
`loggly-jslogger` is more of a "transport" than a full logging framework. It does not care what you send. You can send for example `{"level":"INFO","message":"my log message"}` and Loggly will parse `level` and `message` out of it and lets you search for them. You can create own wrapper functions `logInfo()`, `logWarn()` etc. and tweak the format according to your needs.
