### ISSUE TITLE
Any plans to make this library available on npm?

### ISSUE THREAD

**Issue by varshneyjayant** [loggly/loggly-jslogger#81]
If yes, I can submit a PR.

**Comment by michal-bures** [comment]
The library is already available on npm https://www.npmjs.com/package/loggly-jslogger. I can see it would be good to mention that in the README though. Feel free to reopen if it doesn't work for you or if I misunderstood your issue.

**Comment by cspollar** [comment]
I've [opened a PR](https://github.com/loggly/loggly-jslogger/pull/86) to add a npm link to the README. The clear indicator that the npm package is officially supported would have saved me some time.
